### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by suenalaba** [suenalaba/pe#13]
For method parameters, some classes are documented by parameter type while some are documented by parameter name. While this is unlikely to affect the application directly, it can certainly help future developers if there is more consistent documentation used!
Eg: hasAppointmentToday(String, string)  vs edit(medicineName, dosage, type.... )
![6e14f50a45c1da8423a89fa31c7ffa04.png](https://raw.githubusercontent.com/suenalaba/pe/main/files/b7759677-e3bb-4580-9869-d0d379fcc016.png)
![9dd9b0dae10e7480fac3bdc295ec20bd.png](https://raw.githubusercontent.com/suenalaba/pe/main/files/a54ba7d1-7eea-4302-a17d-a73f50d5986f.png)

**Comment by nus-pe-script** [comment]
# Team's Response
We did that because the classes that have "List" as a suffix to their name is more general compared to asset classes that are more precise


# Items for the Tester to Verify
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Low`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
