### ISSUE TITLE
invalid method in PatientList class diagram

### ISSUE THREAD

**Issue by suenalaba** [suenalaba/pe#16]
search()(String) is not a valid method.
![7d1cbc38dd3bcc97fb640c799e85319f.png](https://raw.githubusercontent.com/suenalaba/pe/main/files/043a6a39-7e2b-484d-9f5e-c8f7dd289a33.png)

**Comment by nus-se-script** [comment]
# Team's Response
Severity is Very Low instead of just Low. It is a very very minor typo.


# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.Rejected`]



- [x] I disagree

**Reason for disagreement:** Agree that its a minor typo hence agree to the proposed very low severity

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Low`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
