### ISSUE TITLE
Validator class diagram documentation errors

### ISSUE THREAD

**Issue by suenalaba** [suenalaba/pe#19]
Incorrect parameter types are shown/inconsistent and is confusing. Many different types of string(], string] string()] can be seen
![956751bba2fce1df6daee0c0ab5806d7.png](https://raw.githubusercontent.com/suenalaba/pe/main/files/8bb06010-3e33-447f-afa0-393fd664aecb.png)

**Comment by nus-pe-script** [comment]
# Team's Response
No details provided by team.


# Items for the Tester to Verify
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Medium`]

- [x] I disagree

**Reason for disagreement:** I feel that at minimal this is a low severity. Simply because, it greatly reduces readability and understanding.

-------------------
